import React, { useState } from 'react';
import './CreateChallan.css';

// Icon components
const Receipt = ({ className }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5l-5-5 4-4 5 5v6a2 2 0 01-2 2H6a2 2 0 01-2-2V4a2 2 0 012-2h7l5 5v11z" />
    </svg>
);

const Plus = ({ className }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
    </svg>
);

const Save = ({ className }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
    </svg>
);

const Download = ({ className }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
    </svg>
);

const List = ({ className }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 10h16M4 14h16M4 18h16" />
    </svg>
);

const Calendar = ({ className }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 002 2v12a2 2 0 002 2z" />
    </svg>
);

const Search = ({ className }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="m21 21-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
    </svg>
);

const Trash2 = ({ className }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="m19 7-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
    </svg>
);

const Edit3 = ({ className }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
    </svg>
);

const BarChart3 = ({ className }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 13l4-4L11 13l4-4 4 4M3 21h18" />
    </svg>
);

// Types
interface ProductDetail {
    id: string;
    name: string;
    rate: number;
    grossWeight: number;
    dateTime: string;
    netWeight: number;
    lessWeight: number;
    gtWeight: number;
    amount: number;
}

interface WeightDetail {
    tareWeight: number;
    dateTime: string;
    netWeight: number;
    lessWeight: number;
    totalGTWeight: number;
    vehicleCommission: number;
}

interface ChallanFormData {
    challanNo: string;
    financialYear: string;
    autoGenerated: boolean;
    dateTime: string;
    paymentType: 'cash' | 'credit';

    // Consignee details
    consignee: string;
    address: string;
    state: string;
    district: string;
    pin: string;
    contact: string;
    emailId: string;

    // Vehicle details
    advAmount: number;
    vehicleType: string;
    vehicleNo: string;
    vehicleRemarks: string;
    driverName: string;
    driverNumber: string;

    // GST details
    gstBill: boolean;
    gstNumber: string;
    gstName: string;
    gstAddress: string;
    gstState: string;
    gstDistrict: string;
    gstPin: string;

    // Additional fields
    endUser: boolean;
    dealer: boolean;
    balance: number;
    limit: number;

    // Product and weight details
    productDetails: ProductDetail[];
    weightDetails: WeightDetail;

    // Amount details
    amount: number;
    loading: number;
    commission: number;
    total: number;
    gstAmount: number;
    royalty: number;
    tpAmount: number;
    freightAmt: number;
    extraAmt: number;
    grandTotal: number;
}

export default function CreateChallan() {
    const [activeTab, setActiveTab] = useState('history');
    const [challanData, setChallanData] = useState<ChallanFormData>({
        challanNo: 'S',
        financialYear: '2025-2026',
        autoGenerated: true,
        dateTime: '23/07/2025 19:57:00',
        paymentType: 'cash',

        consignee: '',
        address: '',
        state: '',
        district: '',
        pin: '',
        contact: '',
        emailId: '',

        advAmount: 0,
        vehicleType: '',
        vehicleNo: '',
        vehicleRemarks: '',
        driverName: '',
        driverNumber: '',

        gstBill: false,
        gstNumber: '',
        gstName: '',
        gstAddress: '',
        gstState: '',
        gstDistrict: '',
        gstPin: '',

        endUser: true,
        dealer: false,
        balance: 0,
        limit: 0,

        productDetails: [],
        weightDetails: {
            tareWeight: 0,
            dateTime: '',
            netWeight: 0,
            lessWeight: 0,
            totalGTWeight: 0,
            vehicleCommission: 0,
        },

        amount: 0,
        loading: 0,
        commission: 0,
        total: 0,
        gstAmount: 0,
        royalty: 0,
        tpAmount: 0,
        freightAmt: 0,
        extraAmt: 0,
        grandTotal: 0,
    });

    const [productDetails, setProductDetails] = useState<ProductDetail[]>([
        {
            id: '1',
            name: '',
            rate: 0,
            grossWeight: 0,
            dateTime: '',
            netWeight: 0,
            lessWeight: 0,
            gtWeight: 0,
            amount: 0,
        },
    ]);

    // Demo challan history data
    const [challanHistory] = useState([
        {
            id: 'CHN001',
            challanNo: 'S/2025-2026/001',
            date: '2025-07-24',
            time: '09:30:00',
            consignee: 'ABC Construction Ltd.',
            vehicleNo: 'MH12AB1234',
            driverName: 'Rajesh Kumar',
            productName: 'Crushed Stone',
            quantity: 15.5,
            amount: 125000,
            status: 'Completed',
            paymentType: 'Cash'
        },
        {
            id: 'CHN002',
            challanNo: 'S/2025-2026/002',
            date: '2025-07-24',
            time: '11:15:00',
            consignee: 'XYZ Builders Pvt Ltd',
            vehicleNo: 'MH14CD5678',
            driverName: 'Suresh Patil',
            productName: 'River Sand',
            quantity: 12.0,
            amount: 85000,
            status: 'In Transit',
            paymentType: 'Credit'
        },
        {
            id: 'CHN003',
            challanNo: 'S/2025-2026/003',
            date: '2025-07-23',
            time: '14:45:00',
            consignee: 'Metro Infrastructure',
            vehicleNo: 'MH16EF9012',
            driverName: 'Amit Sharma',
            productName: 'Gravel',
            quantity: 18.2,
            amount: 95000,
            status: 'Completed',
            paymentType: 'Cash'
        },
        {
            id: 'CHN004',
            challanNo: 'S/2025-2026/004',
            date: '2025-07-23',
            time: '16:20:00',
            consignee: 'Sai Construction',
            vehicleNo: 'MH18GH3456',
            driverName: 'Vikram Singh',
            productName: 'M-Sand',
            quantity: 20.0,
            amount: 110000,
            status: 'Pending',
            paymentType: 'Credit'
        },
        {
            id: 'CHN005',
            challanNo: 'S/2025-2026/005',
            date: '2025-07-22',
            time: '10:30:00',
            consignee: 'Royal Developers',
            vehicleNo: 'MH20IJ7890',
            driverName: 'Mahesh Yadav',
            productName: 'Crushed Stone',
            quantity: 16.8,
            amount: 135000,
            status: 'Completed',
            paymentType: 'Cash'
        },
        {
            id: 'CHN006',
            challanNo: 'S/2025-2026/006',
            date: '2025-07-22',
            time: '13:15:00',
            consignee: 'Green Build Solutions',
            vehicleNo: 'MH22KL2345',
            driverName: 'Ravi Desai',
            productName: 'River Sand',
            quantity: 14.5,
            amount: 98000,
            status: 'In Transit',
            paymentType: 'Credit'
        },
        {
            id: 'CHN007',
            challanNo: 'S/2025-2026/007',
            date: '2025-07-21',
            time: '08:45:00',
            consignee: 'Prime Infrastructure',
            vehicleNo: 'MH24MN6789',
            driverName: 'Deepak Joshi',
            productName: 'Aggregate',
            quantity: 22.1,
            amount: 155000,
            status: 'Completed',
            paymentType: 'Cash'
        },
        {
            id: 'CHN008',
            challanNo: 'S/2025-2026/008',
            date: '2025-07-21',
            time: '15:30:00',
            consignee: 'Skyline Constructions',
            vehicleNo: 'MH26OP0123',
            driverName: 'Santosh Pawar',
            productName: 'Stone Chips',
            quantity: 19.3,
            amount: 142000,
            status: 'Completed',
            paymentType: 'Credit'
        },
        {
            id: 'CHN009',
            challanNo: 'S/2025-2026/009',
            date: '2025-07-20',
            time: '11:00:00',
            consignee: 'Unity Builders',
            vehicleNo: 'MH28QR4567',
            driverName: 'Ganesh Kulkarni',
            productName: 'Crushed Stone',
            quantity: 17.6,
            amount: 128000,
            status: 'Cancelled',
            paymentType: 'Cash'
        },
        {
            id: 'CHN010',
            challanNo: 'S/2025-2026/010',
            date: '2025-07-20',
            time: '17:15:00',
            consignee: 'Modern Contractors',
            vehicleNo: 'MH30ST8901',
            driverName: 'Pravin Jadhav',
            productName: 'M-Sand',
            quantity: 21.4,
            amount: 118000,
            status: 'Completed',
            paymentType: 'Credit'
        }
    ]);

    // Filter states for history
    const [historyFilters, setHistoryFilters] = useState({
        searchTerm: '',
        dateFrom: '',
        dateTo: '',
        status: '',
        paymentType: '',
        consignee: ''
    });

    // Filtered history data
    const filteredHistory = challanHistory.filter(challan => {
        const matchesSearch = challan.challanNo.toLowerCase().includes(historyFilters.searchTerm.toLowerCase()) ||
            challan.consignee.toLowerCase().includes(historyFilters.searchTerm.toLowerCase()) ||
            challan.vehicleNo.toLowerCase().includes(historyFilters.searchTerm.toLowerCase()) ||
            challan.driverName.toLowerCase().includes(historyFilters.searchTerm.toLowerCase());

        const matchesDateFrom = !historyFilters.dateFrom || challan.date >= historyFilters.dateFrom;
        const matchesDateTo = !historyFilters.dateTo || challan.date <= historyFilters.dateTo;
        const matchesStatus = !historyFilters.status || challan.status === historyFilters.status;
        const matchesPaymentType = !historyFilters.paymentType || challan.paymentType === historyFilters.paymentType;
        const matchesConsignee = !historyFilters.consignee || challan.consignee.toLowerCase().includes(historyFilters.consignee.toLowerCase());

        return matchesSearch && matchesDateFrom && matchesDateTo && matchesStatus && matchesPaymentType && matchesConsignee;
    });

    const handleInputChange = (field: keyof ChallanFormData, value: any) => {
        setChallanData(prev => ({
            ...prev,
            [field]: value,
        }));
    };

    const addProductDetail = () => {
        const newProduct: ProductDetail = {
            id: Date.now().toString(),
            name: '',
            rate: 0,
            grossWeight: 0,
            dateTime: '',
            netWeight: 0,
            lessWeight: 0,
            gtWeight: 0,
            amount: 0,
        };
        setProductDetails([...productDetails, newProduct]);
    };

    const removeProductDetail = (id: string) => {
        setProductDetails(productDetails.filter(product => product.id !== id));
    };

    const updateProductDetail = (id: string, field: keyof ProductDetail, value: any) => {
        setProductDetails(productDetails.map(product =>
            product.id === id ? { ...product, [field]: value } : product
        ));
    };

    const calculateTotals = () => {
        const subtotal = challanData.amount + challanData.loading + challanData.commission;
        const grandTotal = subtotal + challanData.gstAmount + challanData.royalty +
            challanData.tpAmount + challanData.freightAmt + challanData.extraAmt;

        handleInputChange('total', subtotal);
        handleInputChange('grandTotal', grandTotal);
    };

    const saveChallan = () => {
        console.log('Saving challan:', challanData);
        // Implement save logic
        alert('Challan saved successfully!');
    };

    const printChallan = () => {
        window.print();
    };

    return (
        <div className="challan-screen">
            {/* Header */}
            <div className="challan-screen-header">
                <div className="challan-screen-header-content">
                    <div className="challan-screen-title-section">
                        <Receipt className="challan-screen-header-icon" />
                        <div>
                            <h1 className="challan-screen-title">Challan Management</h1>
                            <p className="challan-screen-subtitle">Create and manage mining transport challans</p>
                        </div>
                    </div>
                    <div className="challan-screen-header-actions">
                        <button className="challan-screen-btn challan-screen-btn-secondary" onClick={printChallan}>
                            <Download className="challan-screen-icon" />
                            Print
                        </button>
                        <button className="challan-screen-btn challan-screen-btn-primary" onClick={saveChallan}>
                            <Save className="challan-screen-icon" />
                            Save Challan
                        </button>
                    </div>
                </div>
            </div>

            {/* Main Content */}
            <div className="challan-screen-main">
                {/* Tabs */}
                <div className="challan-screen-tabs">
                    <div className="challan-screen-tabs-container">
                        <nav className="challan-screen-tabs-nav">
                            <div className="challan-screen-tabs-list">
                                <button
                                    className={`challan-screen-tab ${activeTab === 'history' ? 'active' : ''}`}
                                    onClick={() => setActiveTab('history')}
                                >
                                    <List className="challan-screen-tab-icon" />
                                    Challan History
                                </button>
                                <button
                                    className={`challan-screen-tab ${activeTab === 'create' ? 'active' : ''}`}
                                    onClick={() => setActiveTab('create')}
                                >
                                    <Plus className="challan-screen-tab-icon" />
                                    Create Challan
                                </button>

                            </div>
                        </nav>
                    </div>
                </div>

                {/* Create Challan Tab */}
                <div className={`challan-screen-tab-content ${activeTab === 'create' ? 'active' : ''}`}>
                    <div className="challan-screen-form-container">

                        {/* Basic Challan Information */}
                        <div className="challan-screen-form-section">
                            <h3 className="challan-screen-form-section-title">
                                <Receipt className="challan-screen-icon" />
                                Challan
                            </h3>

                            <div className="challan-screen-form-row-4">
                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">
                                        Challan No <span className="challan-screen-label-required">*</span>
                                    </label>
                                    <div className="challan-screen-form-group-inline">
                                        <input
                                            type="text"
                                            className="challan-screen-input"
                                            value={challanData.challanNo}
                                            onChange={(e) => handleInputChange('challanNo', e.target.value)}
                                            style={{ width: '60px' }}
                                        />
                                        <span>/</span>
                                        <input
                                            type="text"
                                            className="challan-screen-input"
                                            value={challanData.financialYear}
                                            onChange={(e) => handleInputChange('financialYear', e.target.value)}
                                            style={{ width: '100px' }}
                                        />
                                        <span>/</span>
                                        <span className="challan-screen-text-sm challan-screen-text-gray-600">
                                            Auto Generated
                                        </span>
                                    </div>
                                </div>

                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">Date/Time :</label>
                                    <input
                                        type="datetime-local"
                                        className="challan-screen-input"
                                        value={challanData.dateTime}
                                        onChange={(e) => handleInputChange('dateTime', e.target.value)}
                                    />
                                </div>

                                <div className="challan-screen-form-group-radio">
                                    <label className="challan-screen-flex challan-screen-items-center challan-screen-gap-2">
                                        <input
                                            type="radio"
                                            name="paymentType"
                                            value="cash"
                                            checked={challanData.paymentType === 'cash'}
                                            onChange={(e) => handleInputChange('paymentType', e.target.value)}
                                            className="challan-screen-radio"
                                        />
                                        Cash
                                    </label>
                                    <label className="challan-screen-flex challan-screen-items-center challan-screen-gap-2">
                                        <input
                                            type="radio"
                                            name="paymentType"
                                            value="credit"
                                            checked={challanData.paymentType === 'credit'}
                                            onChange={(e) => handleInputChange('paymentType', e.target.value)}
                                            className="challan-screen-radio"
                                        />
                                        Credit
                                    </label>
                                </div>

                                <div className="challan-screen-balance-section">
                                    <span className="challan-screen-balance-label">Balance :</span>
                                    <span className="challan-screen-balance-value">{challanData.balance}</span>
                                    <div className="challan-screen-limit-section">
                                        <span className="challan-screen-balance-label">Limit :</span>
                                        <span className="challan-screen-balance-value">{challanData.limit}</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Consignee Details */}
                        <div className="challan-screen-form-section">
                            <div className="challan-screen-form-row-2">
                                <div>
                                    <div className="challan-screen-form-group">
                                        <label className="challan-screen-label">
                                            Consignee <span className="challan-screen-label-required">*</span>
                                        </label>
                                        <div className="challan-screen-form-group-inline">
                                            <select className="challan-screen-select" style={{ flex: 1 }}>
                                                <option value="">Select Consignee</option>
                                                <option value="consignee1">Consignee 1</option>
                                                <option value="consignee2">Consignee 2</option>
                                            </select>
                                            <button className="challan-screen-btn-icon" style={{ backgroundColor: 'orange', color: 'white' }}>
                                                <Search className="challan-screen-icon-sm" />
                                            </button>
                                        </div>
                                    </div>

                                    <div className="challan-screen-form-group">
                                        <label className="challan-screen-label">Address :</label>
                                        <textarea
                                            className="challan-screen-textarea"
                                            rows={3}
                                            value={challanData.address}
                                            onChange={(e) => handleInputChange('address', e.target.value)}
                                        />
                                    </div>

                                    <div className="challan-screen-form-row-2">
                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">State :</label>
                                            <select
                                                className="challan-screen-select"
                                                value={challanData.state}
                                                onChange={(e) => handleInputChange('state', e.target.value)}
                                            >
                                                <option value="">Select State</option>
                                                <option value="maharashtra">Maharashtra</option>
                                                <option value="gujarat">Gujarat</option>
                                                <option value="karnataka">Karnataka</option>
                                            </select>
                                        </div>

                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">District :</label>
                                            <select
                                                className="challan-screen-select"
                                                value={challanData.district}
                                                onChange={(e) => handleInputChange('district', e.target.value)}
                                            >
                                                <option value="">Select District</option>
                                                <option value="pune">Pune</option>
                                                <option value="mumbai">Mumbai</option>
                                                <option value="nagpur">Nagpur</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div className="challan-screen-form-row-3">
                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">PIN :</label>
                                            <select
                                                className="challan-screen-select"
                                                value={challanData.pin}
                                                onChange={(e) => handleInputChange('pin', e.target.value)}
                                            >
                                                <option value="">Select PIN</option>
                                                <option value="411001">411001</option>
                                                <option value="411002">411002</option>
                                                <option value="411003">411003</option>
                                            </select>
                                        </div>

                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">Contact# :</label>
                                            <input
                                                type="tel"
                                                className="challan-screen-input"
                                                value={challanData.contact}
                                                onChange={(e) => handleInputChange('contact', e.target.value)}
                                            />
                                        </div>

                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">EmailID :</label>
                                            <input
                                                type="email"
                                                className="challan-screen-input"
                                                value={challanData.emailId}
                                                onChange={(e) => handleInputChange('emailId', e.target.value)}
                                            />
                                        </div>
                                    </div>
                                </div>

                                <div>
                                    <div className="challan-screen-form-group">
                                        <label className="challan-screen-label">Adv. Amount :</label>
                                        <input
                                            type="number"
                                            className="challan-screen-input"
                                            value={challanData.advAmount}
                                            onChange={(e) => handleInputChange('advAmount', parseFloat(e.target.value) || 0)}
                                        />
                                    </div>

                                    <div className="challan-screen-form-group">
                                        <label className="challan-screen-label">Vehicle Type :</label>
                                        <div className="challan-screen-form-group-inline">
                                            <select className="challan-screen-select" style={{ flex: 1 }}>
                                                <option value="">Select Vehicle Type</option>
                                                <option value="truck">Truck</option>
                                                <option value="trailer">Trailer</option>
                                                <option value="dumper">Dumper</option>
                                            </select>
                                            <button className="challan-screen-btn-icon" style={{ backgroundColor: 'orange', color: 'white' }}>
                                                <Search className="challan-screen-icon-sm" />
                                            </button>
                                        </div>
                                    </div>

                                    <div className="challan-screen-form-group">
                                        <label className="challan-screen-label">Vehicle No :</label>
                                        <div className="challan-screen-form-group-inline">
                                            <select className="challan-screen-select" style={{ flex: 1 }}>
                                                <option value="">Select Vehicle No</option>
                                                <option value="MH12AB1234">MH12AB1234</option>
                                                <option value="MH14CD5678">MH14CD5678</option>
                                            </select>
                                            <button className="challan-screen-btn-icon" style={{ backgroundColor: 'orange', color: 'white' }}>
                                                <Search className="challan-screen-icon-sm" />
                                            </button>
                                        </div>
                                    </div>

                                    <div className="challan-screen-form-group">
                                        <label className="challan-screen-label">Vehicle Remarks :</label>
                                        <textarea
                                            className="challan-screen-textarea"
                                            rows={2}
                                            value={challanData.vehicleRemarks}
                                            onChange={(e) => handleInputChange('vehicleRemarks', e.target.value)}
                                        />
                                    </div>

                                    <div className="challan-screen-form-row-2">
                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">Driver Name :</label>
                                            <input
                                                type="text"
                                                className="challan-screen-input"
                                                value={challanData.driverName}
                                                onChange={(e) => handleInputChange('driverName', e.target.value)}
                                            />
                                        </div>

                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">Driver# :</label>
                                            <input
                                                type="tel"
                                                className="challan-screen-input"
                                                value={challanData.driverNumber}
                                                onChange={(e) => handleInputChange('driverNumber', e.target.value)}
                                            />
                                        </div>
                                    </div>

                                    <div className="challan-screen-form-group-radio">
                                        <label className="challan-screen-flex challan-screen-items-center challan-screen-gap-2">
                                            <input
                                                type="radio"
                                                name="userType"
                                                value="endUser"
                                                checked={challanData.endUser}
                                                onChange={(e) => handleInputChange('endUser', e.target.checked)}
                                                className="challan-screen-radio"
                                            />
                                            End-User
                                        </label>
                                        <label className="challan-screen-flex challan-screen-items-center challan-screen-gap-2">
                                            <input
                                                type="radio"
                                                name="userType"
                                                value="dealer"
                                                checked={challanData.dealer}
                                                onChange={(e) => handleInputChange('dealer', e.target.checked)}
                                                className="challan-screen-radio"
                                            />
                                            Dealer
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* GST Details */}
                        <div className="challan-screen-form-section">
                            <div className="challan-screen-form-row-2">
                                <div>
                                    <div className="challan-screen-form-group">
                                        <label className="challan-screen-flex challan-screen-items-center challan-screen-gap-2">
                                            <input
                                                type="checkbox"
                                                checked={challanData.gstBill}
                                                onChange={(e) => handleInputChange('gstBill', e.target.checked)}
                                                className="challan-screen-checkbox"
                                            />
                                            GST Bill
                                        </label>
                                    </div>

                                    <div className="challan-screen-form-group">
                                        <label className="challan-screen-label">GST# :</label>
                                        <input
                                            type="text"
                                            className="challan-screen-input"
                                            value={challanData.gstNumber}
                                            onChange={(e) => handleInputChange('gstNumber', e.target.value)}
                                            disabled={!challanData.gstBill}
                                        />
                                    </div>
                                </div>

                                <div>
                                    <div className="challan-screen-form-group">
                                        <label className="challan-screen-label">Name :</label>
                                        <div className="challan-screen-form-group-inline">
                                            <select
                                                className="challan-screen-select"
                                                style={{ flex: 1 }}
                                                disabled={!challanData.gstBill}
                                            >
                                                <option value="">Select Name</option>
                                                <option value="company1">Company 1</option>
                                                <option value="company2">Company 2</option>
                                            </select>
                                            <button
                                                className="challan-screen-btn-icon"
                                                style={{ backgroundColor: 'orange', color: 'white' }}
                                                disabled={!challanData.gstBill}
                                            >
                                                <Search className="challan-screen-icon-sm" />
                                            </button>
                                        </div>
                                    </div>

                                    <div className="challan-screen-form-group">
                                        <label className="challan-screen-label">Address :</label>
                                        <textarea
                                            className="challan-screen-textarea"
                                            rows={2}
                                            value={challanData.gstAddress}
                                            onChange={(e) => handleInputChange('gstAddress', e.target.value)}
                                            disabled={!challanData.gstBill}
                                        />
                                    </div>

                                    <div className="challan-screen-form-row-3">
                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">State :</label>
                                            <select
                                                className="challan-screen-select"
                                                value={challanData.gstState}
                                                onChange={(e) => handleInputChange('gstState', e.target.value)}
                                                disabled={!challanData.gstBill}
                                            >
                                                <option value="">Select State</option>
                                                <option value="maharashtra">Maharashtra</option>
                                                <option value="gujarat">Gujarat</option>
                                            </select>
                                        </div>

                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">District :</label>
                                            <select
                                                className="challan-screen-select"
                                                value={challanData.gstDistrict}
                                                onChange={(e) => handleInputChange('gstDistrict', e.target.value)}
                                                disabled={!challanData.gstBill}
                                            >
                                                <option value="">Select District</option>
                                                <option value="pune">Pune</option>
                                                <option value="mumbai">Mumbai</option>
                                            </select>
                                        </div>

                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">PIN :</label>
                                            <select
                                                className="challan-screen-select"
                                                value={challanData.gstPin}
                                                onChange={(e) => handleInputChange('gstPin', e.target.value)}
                                                disabled={!challanData.gstBill}
                                            >
                                                <option value="">Select PIN</option>
                                                <option value="411001">411001</option>
                                                <option value="411002">411002</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Product Detail */}
                        <div className="challan-screen-form-section">
                            <div className="challan-screen-flex challan-screen-items-center challan-screen-justify-between challan-screen-mb-6">
                                <h3 className="challan-screen-form-section-title">
                                    Product Detail
                                </h3>
                                <button
                                    className="challan-screen-btn challan-screen-btn-primary"
                                    onClick={addProductDetail}
                                >
                                    <Plus className="challan-screen-icon" />
                                    Add Product
                                </button>
                            </div>

                            <div className="challan-screen-table-container">
                                <table className="challan-screen-table">
                                    <thead>
                                        <tr>
                                            <th>S.No</th>
                                            <th>Name</th>
                                            <th>Rate</th>
                                            <th>Gross Weight</th>
                                            <th>Date/Time</th>
                                            <th>Net Weight</th>
                                            <th>Less Weight</th>
                                            <th>GT Weight</th>
                                            <th>Amount</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {productDetails.map((product, index) => (
                                            <tr key={product.id}>
                                                <td>{index + 1}</td>
                                                <td>
                                                    <select
                                                        className="challan-screen-select"
                                                        value={product.name}
                                                        onChange={(e) => updateProductDetail(product.id, 'name', e.target.value)}
                                                    >
                                                        <option value="">Select Product</option>
                                                        <option value="stone">Stone</option>
                                                        <option value="sand">Sand</option>
                                                        <option value="gravel">Gravel</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <input
                                                        type="number"
                                                        className="challan-screen-input"
                                                        value={product.rate}
                                                        onChange={(e) => updateProductDetail(product.id, 'rate', parseFloat(e.target.value) || 0)}
                                                        style={{ width: '80px' }}
                                                    />
                                                </td>
                                                <td>
                                                    <input
                                                        type="number"
                                                        className="challan-screen-input"
                                                        value={product.grossWeight}
                                                        onChange={(e) => updateProductDetail(product.id, 'grossWeight', parseFloat(e.target.value) || 0)}
                                                        style={{ width: '100px' }}
                                                    />
                                                </td>
                                                <td>
                                                    <input
                                                        type="datetime-local"
                                                        className="challan-screen-input"
                                                        value={product.dateTime}
                                                        onChange={(e) => updateProductDetail(product.id, 'dateTime', e.target.value)}
                                                        style={{ width: '160px' }}
                                                    />
                                                </td>
                                                <td>
                                                    <input
                                                        type="number"
                                                        className="challan-screen-input"
                                                        value={product.netWeight}
                                                        onChange={(e) => updateProductDetail(product.id, 'netWeight', parseFloat(e.target.value) || 0)}
                                                        style={{ width: '100px' }}
                                                    />
                                                </td>
                                                <td>
                                                    <input
                                                        type="number"
                                                        className="challan-screen-input"
                                                        value={product.lessWeight}
                                                        onChange={(e) => updateProductDetail(product.id, 'lessWeight', parseFloat(e.target.value) || 0)}
                                                        style={{ width: '100px' }}
                                                    />
                                                </td>
                                                <td>
                                                    <input
                                                        type="number"
                                                        className="challan-screen-input"
                                                        value={product.gtWeight}
                                                        onChange={(e) => updateProductDetail(product.id, 'gtWeight', parseFloat(e.target.value) || 0)}
                                                        style={{ width: '100px' }}
                                                    />
                                                </td>
                                                <td>
                                                    <input
                                                        type="number"
                                                        className="challan-screen-input"
                                                        value={product.amount}
                                                        onChange={(e) => updateProductDetail(product.id, 'amount', parseFloat(e.target.value) || 0)}
                                                        style={{ width: '100px' }}
                                                    />
                                                </td>
                                                <td>
                                                    {productDetails.length > 1 && (
                                                        <button
                                                            className="challan-screen-btn-icon challan-screen-btn-icon-danger"
                                                            onClick={() => removeProductDetail(product.id)}
                                                        >
                                                            <Trash2 className="challan-screen-icon-sm" />
                                                        </button>
                                                    )}
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        {/* Weight Detail */}
                        <div className="challan-screen-form-section">
                            <h3 className="challan-screen-form-section-title">Weight Detail</h3>

                            <div className="challan-screen-form-row-6">
                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">Tare Weight</label>
                                    <input
                                        type="number"
                                        className="challan-screen-input"
                                        value={challanData.weightDetails.tareWeight}
                                        onChange={(e) => handleInputChange('weightDetails', {
                                            ...challanData.weightDetails,
                                            tareWeight: parseFloat(e.target.value) || 0
                                        })}
                                    />
                                </div>

                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">Date/Time</label>
                                    <input
                                        type="datetime-local"
                                        className="challan-screen-input"
                                        value={challanData.weightDetails.dateTime}
                                        onChange={(e) => handleInputChange('weightDetails', {
                                            ...challanData.weightDetails,
                                            dateTime: e.target.value
                                        })}
                                    />
                                </div>

                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">Net Weight</label>
                                    <input
                                        type="number"
                                        className="challan-screen-input"
                                        value={challanData.weightDetails.netWeight}
                                        onChange={(e) => handleInputChange('weightDetails', {
                                            ...challanData.weightDetails,
                                            netWeight: parseFloat(e.target.value) || 0
                                        })}
                                    />
                                </div>

                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">Less Weight</label>
                                    <input
                                        type="number"
                                        className="challan-screen-input"
                                        value={challanData.weightDetails.lessWeight}
                                        onChange={(e) => handleInputChange('weightDetails', {
                                            ...challanData.weightDetails,
                                            lessWeight: parseFloat(e.target.value) || 0
                                        })}
                                    />
                                </div>

                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">Total GT Weight</label>
                                    <input
                                        type="number"
                                        className="challan-screen-input"
                                        value={challanData.weightDetails.totalGTWeight}
                                        onChange={(e) => handleInputChange('weightDetails', {
                                            ...challanData.weightDetails,
                                            totalGTWeight: parseFloat(e.target.value) || 0
                                        })}
                                    />
                                </div>

                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">Vehicle Commission</label>
                                    <input
                                        type="number"
                                        className="challan-screen-input"
                                        value={challanData.weightDetails.vehicleCommission}
                                        onChange={(e) => handleInputChange('weightDetails', {
                                            ...challanData.weightDetails,
                                            vehicleCommission: parseFloat(e.target.value) || 0
                                        })}
                                    />
                                </div>
                            </div>
                        </div>

                        {/* Amount Detail */}
                        <div className="challan-screen-form-section">
                            <h3 className="challan-screen-form-section-title">Amount Detail</h3>

                            <div className="challan-screen-form-row-2">
                                <div>
                                    <div className="challan-screen-form-row-3">
                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">Amount</label>
                                            <input
                                                type="number"
                                                className="challan-screen-input"
                                                value={challanData.amount}
                                                onChange={(e) => handleInputChange('amount', parseFloat(e.target.value) || 0)}
                                            />
                                        </div>

                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">Loading</label>
                                            <input
                                                type="number"
                                                className="challan-screen-input"
                                                value={challanData.loading}
                                                onChange={(e) => handleInputChange('loading', parseFloat(e.target.value) || 0)}
                                            />
                                        </div>

                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">Commission</label>
                                            <input
                                                type="number"
                                                className="challan-screen-input"
                                                value={challanData.commission}
                                                onChange={(e) => handleInputChange('commission', parseFloat(e.target.value) || 0)}
                                            />
                                        </div>
                                    </div>

                                    <div className="challan-screen-form-row-4">
                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">GST Amount</label>
                                            <input
                                                type="number"
                                                className="challan-screen-input"
                                                value={challanData.gstAmount}
                                                onChange={(e) => handleInputChange('gstAmount', parseFloat(e.target.value) || 0)}
                                            />
                                        </div>

                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">Royalty</label>
                                            <input
                                                type="number"
                                                className="challan-screen-input"
                                                value={challanData.royalty}
                                                onChange={(e) => handleInputChange('royalty', parseFloat(e.target.value) || 0)}
                                            />
                                        </div>

                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">TP Amount</label>
                                            <input
                                                type="number"
                                                className="challan-screen-input"
                                                value={challanData.tpAmount}
                                                onChange={(e) => handleInputChange('tpAmount', parseFloat(e.target.value) || 0)}
                                            />
                                        </div>

                                        <div className="challan-screen-form-group">
                                            <label className="challan-screen-label">Freight Amt</label>
                                            <input
                                                type="number"
                                                className="challan-screen-input"
                                                value={challanData.freightAmt}
                                                onChange={(e) => handleInputChange('freightAmt', parseFloat(e.target.value) || 0)}
                                            />
                                        </div>
                                    </div>
                                </div>

                                <div className="challan-screen-summary">
                                    <div className="challan-screen-summary-row">
                                        <span className="challan-screen-summary-label">Total</span>
                                        <span className="challan-screen-summary-value">{challanData.total}</span>
                                    </div>
                                    <div className="challan-screen-summary-row">
                                        <span className="challan-screen-summary-label">Extra Amount</span>
                                        <input
                                            type="number"
                                            className="challan-screen-input"
                                            value={challanData.extraAmt}
                                            onChange={(e) => handleInputChange('extraAmt', parseFloat(e.target.value) || 0)}
                                            style={{ width: '120px', textAlign: 'right' }}
                                        />
                                    </div>
                                    <div className="challan-screen-summary-row">
                                        <span className="challan-screen-summary-label">Grand Total</span>
                                        <span className="challan-screen-summary-value">{challanData.grandTotal}</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Action Buttons */}
                        <div className="challan-screen-action-buttons">
                            <button className="challan-screen-btn challan-screen-btn-secondary">
                                Cancel
                            </button>
                            <button
                                className="challan-screen-btn challan-screen-btn-primary"
                                onClick={calculateTotals}
                            >
                                Calculate
                            </button>
                            <button
                                className="challan-screen-btn challan-screen-btn-primary"
                                onClick={saveChallan}
                            >
                                <Save className="challan-screen-icon" />
                                Save Challan
                            </button>
                        </div>
                    </div>
                </div>

                {/* Challan History Tab */}
                <div className={`challan-screen-tab-content ${activeTab === 'history' ? 'active' : ''}`}>
                    <div className="challan-screen-form-container">

                        {/* Search and Filter Section */}
                        <div className="challan-screen-form-section">
                            <h3 className="challan-screen-form-section-title">
                                <Search className="challan-screen-icon" />
                                Search & Filter Challans
                            </h3>

                            <div className="challan-screen-form-row-3">
                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">Search</label>
                                    <div className="challan-screen-form-group-inline">
                                        <Search className="challan-screen-icon-sm" style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: '#6b7280', pointerEvents: 'none' }} />
                                        <input
                                            type="text"
                                            className="challan-screen-input"
                                            placeholder="Search by Challan No, Consignee, Vehicle No..."
                                            value={historyFilters.searchTerm}
                                            onChange={(e) => setHistoryFilters(prev => ({ ...prev, searchTerm: e.target.value }))}
                                            style={{ paddingLeft: '40px' }}
                                        />
                                    </div>
                                </div>

                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">From Date</label>
                                    <input
                                        type="date"
                                        className="challan-screen-input"
                                        value={historyFilters.dateFrom}
                                        onChange={(e) => setHistoryFilters(prev => ({ ...prev, dateFrom: e.target.value }))}
                                    />
                                </div>

                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">To Date</label>
                                    <input
                                        type="date"
                                        className="challan-screen-input"
                                        value={historyFilters.dateTo}
                                        onChange={(e) => setHistoryFilters(prev => ({ ...prev, dateTo: e.target.value }))}
                                    />
                                </div>
                            </div>

                            <div className="challan-screen-form-row-3">
                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">Status</label>
                                    <select
                                        className="challan-screen-select"
                                        value={historyFilters.status}
                                        onChange={(e) => setHistoryFilters(prev => ({ ...prev, status: e.target.value }))}
                                    >
                                        <option value="">All Status</option>
                                        <option value="Completed">Completed</option>
                                        <option value="In Transit">In Transit</option>
                                        <option value="Pending">Pending</option>
                                        <option value="Cancelled">Cancelled</option>
                                    </select>
                                </div>

                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">Payment Type</label>
                                    <select
                                        className="challan-screen-select"
                                        value={historyFilters.paymentType}
                                        onChange={(e) => setHistoryFilters(prev => ({ ...prev, paymentType: e.target.value }))}
                                    >
                                        <option value="">All Payment Types</option>
                                        <option value="Cash">Cash</option>
                                        <option value="Credit">Credit</option>
                                    </select>
                                </div>

                                <div className="challan-screen-form-group">
                                    <label className="challan-screen-label">Consignee</label>
                                    <input
                                        type="text"
                                        className="challan-screen-input"
                                        placeholder="Filter by Consignee"
                                        value={historyFilters.consignee}
                                        onChange={(e) => setHistoryFilters(prev => ({ ...prev, consignee: e.target.value }))}
                                    />
                                </div>
                            </div>

                            {/* Clear Filters Button */}
                            <div className="challan-screen-form-row-1" style={{ marginTop: '1rem' }}>
                                <button
                                    className="challan-screen-btn challan-screen-btn-secondary"
                                    onClick={() => setHistoryFilters({
                                        searchTerm: '',
                                        dateFrom: '',
                                        dateTo: '',
                                        status: '',
                                        paymentType: '',
                                        consignee: ''
                                    })}
                                >
                                    Clear Filters
                                </button>
                            </div>
                        </div>

                        {/* Summary Statistics */}
                        <div className="challan-screen-form-section">
                            <h3 className="challan-screen-form-section-title">
                                <BarChart3 className="challan-screen-icon" />
                                Summary Statistics
                            </h3>

                            <div className="challan-screen-form-row-4">
                                <div className="challan-screen-summary-card">
                                    <div className="challan-screen-summary-card-content">
                                        <div className="challan-screen-summary-card-title">Total Challans</div>
                                        <div className="challan-screen-summary-card-value">{filteredHistory.length}</div>
                                    </div>
                                </div>

                                <div className="challan-screen-summary-card">
                                    <div className="challan-screen-summary-card-content">
                                        <div className="challan-screen-summary-card-title">Total Amount</div>
                                        <div className="challan-screen-summary-card-value">
                                            ₹{filteredHistory.reduce((sum, challan) => sum + challan.amount, 0).toLocaleString()}
                                        </div>
                                    </div>
                                </div>

                                <div className="challan-screen-summary-card">
                                    <div className="challan-screen-summary-card-content">
                                        <div className="challan-screen-summary-card-title">Total Quantity</div>
                                        <div className="challan-screen-summary-card-value">
                                            {filteredHistory.reduce((sum, challan) => sum + challan.quantity, 0).toFixed(1)} MT
                                        </div>
                                    </div>
                                </div>

                                <div className="challan-screen-summary-card">
                                    <div className="challan-screen-summary-card-content">
                                        <div className="challan-screen-summary-card-title">Completed</div>
                                        <div className="challan-screen-summary-card-value">
                                            {filteredHistory.filter(c => c.status === 'Completed').length}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Challan History Table */}
                        <div className="challan-screen-form-section">
                            <div className="challan-screen-flex challan-screen-items-center challan-screen-justify-between challan-screen-mb-6">
                                <h3 className="challan-screen-form-section-title">
                                    <List className="challan-screen-icon" />
                                    Challan History ({filteredHistory.length} records)
                                </h3>
                                <div className="challan-screen-flex challan-screen-gap-2">
                                    <button className="challan-screen-btn challan-screen-btn-secondary">
                                        <Download className="challan-screen-icon" />
                                        Export Excel
                                    </button>
                                    <button className="challan-screen-btn challan-screen-btn-secondary">
                                        <Download className="challan-screen-icon" />
                                        Export PDF
                                    </button>
                                    <button className="challan-screen-btn challan-screen-btn-primary" onClick={() => setActiveTab('create')}>
                                        <Plus className="challan-screen-icon" />
                                        Create Challan
                                    </button>

                                </div>
                            </div>

                            <div className="challan-screen-table-container" style={{ maxHeight: '600px', overflowY: 'auto' }}>
                                <table className="challan-screen-table">
                                    <thead>
                                        <tr>
                                            <th>S.No</th>
                                            <th>Challan No</th>
                                            <th>Date</th>
                                            <th>Time</th>
                                            <th>Consignee</th>
                                            <th>Vehicle No</th>
                                            <th>Driver Name</th>
                                            <th>Product</th>
                                            <th>Quantity (MT)</th>
                                            <th>Amount (₹)</th>
                                            <th>Payment</th>
                                            <th>Status</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {filteredHistory.length > 0 ? (
                                            filteredHistory.map((challan, index) => (
                                                <tr key={challan.id}>
                                                    <td>{index + 1}</td>
                                                    <td>
                                                        <span className="challan-screen-challan-no">{challan.challanNo}</span>
                                                    </td>
                                                    <td>{new Date(challan.date).toLocaleDateString('en-IN')}</td>
                                                    <td>{challan.time}</td>
                                                    <td>
                                                        <span className="challan-screen-consignee-name">{challan.consignee}</span>
                                                    </td>
                                                    <td>
                                                        <span className="challan-screen-vehicle-no">{challan.vehicleNo}</span>
                                                    </td>
                                                    <td>{challan.driverName}</td>
                                                    <td>{challan.productName}</td>
                                                    <td className="challan-screen-text-right">{challan.quantity.toFixed(1)}</td>
                                                    <td className="challan-screen-text-right">₹{challan.amount.toLocaleString()}</td>
                                                    <td>
                                                        <span className={`challan-screen-payment-badge ${challan.paymentType.toLowerCase()}`}>
                                                            {challan.paymentType}
                                                        </span>
                                                    </td>
                                                    <td>
                                                        <span className={`challan-screen-status-badge ${challan.status.toLowerCase().replace(' ', '-')}`}>
                                                            {challan.status}
                                                        </span>
                                                    </td>
                                                    <td>
                                                        <div className="challan-screen-action-buttons-row">
                                                            <button
                                                                className="challan-screen-btn-icon challan-screen-btn-icon-primary"
                                                                title="View Details"
                                                            >
                                                                <Receipt className="challan-screen-icon-sm" />
                                                            </button>
                                                            <button
                                                                className="challan-screen-btn-icon challan-screen-btn-icon-secondary"
                                                                title="Print Challan"
                                                            >
                                                                <Download className="challan-screen-icon-sm" />
                                                            </button>
                                                            {challan.status === 'Pending' && (
                                                                <button
                                                                    className="challan-screen-btn-icon challan-screen-btn-icon-success"
                                                                    title="Edit Challan"
                                                                >
                                                                    <Edit3 className="challan-screen-icon-sm" />
                                                                </button>
                                                            )}
                                                            {(challan.status === 'Pending' || challan.status === 'In Transit') && (
                                                                <button
                                                                    className="challan-screen-btn-icon challan-screen-btn-icon-danger"
                                                                    title="Cancel Challan"
                                                                >
                                                                    <Trash2 className="challan-screen-icon-sm" />
                                                                </button>
                                                            )}
                                                        </div>
                                                    </td>
                                                </tr>
                                            ))
                                        ) : (
                                            <tr>
                                                <td colSpan={13} className="challan-screen-no-data">
                                                    <div className="challan-screen-no-data-content">
                                                        <Receipt className="challan-screen-no-data-icon" />
                                                        <p>No challans found matching your criteria</p>
                                                        <p className="challan-screen-text-sm">Try adjusting your search filters</p>
                                                    </div>
                                                </td>
                                            </tr>
                                        )}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
